 TS #   DE(kcal/mol)                    Reaction path information
 ====   ============                    =========================
    2        2.6                      MIN   58 <--->                      MIN   96        CONN
    4        3.5                      MIN   58 <--->                      MIN   96        CONN
    5        5.1                      MIN   46 <--->                      MIN  178        CONN
    8       10.1                      MIN  258 <--->                      MIN  369        CONN
    9       10.9                      MIN   40 ---->      PR160:  H2O + C29H19N3O3        CONN
   10       12.6                      MIN  325 <--->                      MIN  407        CONN
   11       12.7                      MIN   26 <--->                      MIN   61        CONN
   12       13.3                      MIN  325 <--->                      MIN  427        CONN
   13       13.5                      MIN  157 ---->      PR144:  H2O + C29H19N3O3        CONN
   14       13.7                      MIN  325 <--->                      MIN  407        CONN
   15       14.3                      MIN  157 ---->      PR143:  H2O + C29H19N3O3        CONN
   16       14.3                      MIN  190 <--->                      MIN  198        CONN
   18       14.9                      MIN   40 ---->      PR154:  H2O + C29H19N3O3        CONN
   20       15.2                      MIN   40 ---->      PR154:  H2O + C29H19N3O3        CONN
   21       16.3                      MIN   19 <--->                      MIN  417        CONN
   23       16.6                      MIN  292 <--->                      MIN  372        CONN
   26       17.1                      MIN    7 <--->                      MIN  157        CONN
   27       17.3                      MIN  241 <--->                      MIN  268        CONN
   28       17.4                      MIN   19 <--->                      MIN  417        CONN
   29       17.7                      MIN    7 <--->                      MIN   45        CONN
   30       19.0                      MIN  164 ---->      PR316:  H2O + C29H19N3O3        CONN
   31       19.2                      MIN  164 ---->      PR316:  H2O + C29H19N3O3        CONN
   32       20.1                      MIN    7 <--->                      MIN  157        CONN
   33       20.8                      MIN  238 ---->      PR294:  H2O + C29H19N3O3        CONN
   34       20.9                      MIN  304 <--->                      MIN  372        CONN
   35       21.5                      MIN  238 ---->      PR294:  H2O + C29H19N3O3        CONN
   37       21.9                      MIN  304 <--->                      MIN  372        CONN
   39       23.0                      MIN  129 <--->                      MIN  230        CONN
   45       24.9                      MIN   68 <--->                      MIN  471        CONN
   46       25.3                      MIN  396 ---->        PR38:  CO + C28H21N3O3        CONN
   49       26.3                      MIN   68 <--->                      MIN  471        CONN
   50       26.6                      MIN   45 <--->                      MIN  157        CONN
   51       26.6                      MIN   71 ---->       PR295:  CO + C28H21N3O3        CONN
   52       26.9                      MIN  719 ---->      PR142:  CO2 + C28H21N3O2        CONN
   53       26.9                      MIN   90 <--->                      MIN  471        CONN
   54       27.5                      MIN   40 <--->                      MIN   46        CONN
   55       27.5                      MIN  116 <--->                      MIN  599        CONN
   56       27.6                      MIN  303 ---->       PR18:  H2O + C29H19N3O3        CONN
   57       27.7                      MIN   26 ---->      PR277:  CO2 + C28H21N3O2        CONN
   59       27.9                      MIN   71 ---->       PR245:  CO + C28H21N3O3        CONN
   61       28.2                      MIN   26 ---->      PR276:  CO2 + C28H21N3O2        CONN
   62       28.2                      MIN  569 ---->       PR301:  CO + C28H21N3O3     DISCONN
   63       28.3                      MIN    2 <--->                      MIN  513        CONN
   64       28.4                      MIN   20 <--->                      MIN   96        CONN
   65       28.5                      MIN  116 <--->                      MIN  599        CONN
   66       28.6                      MIN  442 ---->      PR229:  H2O + C29H19N3O3        CONN
   67       28.6                      MIN   40 <--->                      MIN   46        CONN
   68       29.1                      MIN   71 ---->      PR294:  H2O + C29H19N3O3        CONN
   69       29.1                      MIN  116 <--->                      MIN  599        CONN
   71       29.3                      MIN  135 <--->                      MIN  391        CONN
   72       29.6                      MIN   67 <--->                      MIN   71        CONN
   73       29.8                      MIN  648 <--->                      MIN  688        CONN
   75       29.8                      MIN  303 ---->       PR52:  H2O + C29H19N3O3        CONN
   76       30.0                      MIN   19 <--->                      MIN  646        CONN
   77       30.1                      MIN  179 ---->       PR367:  CO + C28H21N3O3        CONN
   79       30.5                      MIN  303 ---->       PR52:  H2O + C29H19N3O3        CONN
   80       30.5                      MIN   65 <--->                      MIN  103        CONN
   81       30.7                      MIN  303 ---->       PR28:  H2O + C29H19N3O3        CONN
   82       30.8                      MIN   26 ---->      PR276:  CO2 + C28H21N3O2        CONN
   83       31.2                      MIN  303 ---->       PR52:  H2O + C29H19N3O3        CONN
   84       31.5                      MIN   81 <--->                      MIN   67        CONN
   85       31.6                      MIN  219 <--->                      MIN  782        CONN
   89       32.6                      MIN    3 ---->      PR112:  H2O + C29H19N3O3        CONN
   90       32.9                      MIN  252 <--->                      MIN  179        CONN
   91       33.0                      MIN  164 <--->                      MIN  190        CONN
   92       33.0                      MIN  129 <--->                      MIN  135        CONN
   93       33.0                      MIN  206 ---->        PR83:  CO + C28H21N3O3     DISCONN
   94       33.1                      MIN   46 <--->                      MIN  215        CONN
   95       33.2                      MIN   45 <--->                      MIN  728        CONN
   98       33.4                      MIN  141 <--->                      MIN  636        CONN
   99       33.5                      MIN  646 <--->                      MIN  833        CONN
  100       33.7                      MIN  125 <--->                      MIN  751        CONN
  101       33.8                      MIN  141 <--->                      MIN  636        CONN
  102       33.8                      MIN   68 <--->                      MIN  688        CONN
  103       33.8                      MIN   31 <--->                      MIN   58        CONN
  104       34.0                      MIN  666 ---->       PR304:  CO + C28H21N3O3     DISCONN
  105       34.1                      MIN  417 <--->                      MIN  674        CONN
  106       34.2                      MIN  396 ---->      PR212:  CO2 + C28H21N3O2        CONN
  107       34.4                      MIN   28 <--->                      MIN  135        CONN
  108       34.4                      MIN   68 <--->                      MIN  688        CONN
  109       34.8                      MIN  219 <--->                      MIN  782        CONN
  110       34.8                      MIN  161 <--->                      MIN  231        CONN
  111       35.0                      MIN  219 <--->                      MIN  799        CONN
  112       35.2                      MIN  396 ---->      PR213:  CO2 + C28H21N3O2        CONN
  113       35.4                      MIN  252 <--->                      MIN  179        CONN
  114       35.5                      MIN   70 <--->                      MIN  523        CONN
  115       35.7                      MIN   71 <--->                      MIN  673        CONN
  117       36.0                      MIN   71 <--->                      MIN  673        CONN
  119       36.1                      MIN  140 <--->                      MIN  142        CONN
  120       36.1                      MIN  705 <--->                      MIN  837        CONN
  121       36.2                      MIN  209 <--->                      MIN  264        CONN
  122       36.2                      MIN   81 <--->                      MIN  130        CONN
  123       36.3                      MIN   70 <--->                      MIN  665        CONN
  124       36.3                      MIN  673 <--->                      MIN  730        CONN
  125       36.4                      MIN  665 <--->                      MIN  867        CONN
  127       36.7                      MIN  268 <--->                      MIN  799        CONN
  128       37.0                      MIN  566 <--->                      MIN  728        CONN
  130       37.1                      MIN  782 ---->      PR251:  H2O + C29H19N3O3        CONN
  133       37.3                      MIN   26 <--->                      MIN  165        CONN
  134       37.3                      MIN  252 ---->    PR342:  CH2O2 + C28H19N3O2        CONN
  135       37.5                      MIN  150 <--->                      MIN  183        CONN
  136       37.7                      MIN  258 ---->        PR45:  H2 + C29H19N3O4        CONN
  138       38.0                      MIN  198 ---->      PR316:  H2O + C29H19N3O3        CONN
  139       38.5                      MIN   68 ---->    PR197:  CH2O2 + C28H19N3O2        CONN
  140       38.5                      MIN  157 <--->                      MIN  728        CONN
  141       38.6                      MIN   31 <--->                      MIN   96        CONN
  143       38.8                      MIN   26 <--->                      MIN  165        CONN
  144       38.9                      MIN   45 ---->      PR143:  H2O + C29H19N3O3        CONN
  145       38.9                      MIN  719 ---->       PR117:  CO + C28H21N3O3        CONN
  146       39.0                      MIN   68 ---->    PR186:  CH2O2 + C28H19N3O2        CONN
  147       39.0                      MIN  264 <--->                      MIN  203        CONN
  149       39.1                      MIN   68 ---->    PR210:  CH2O2 + C28H19N3O2        CONN
  150       39.1                      MIN   19 <--->                      MIN  892        CONN
  151       39.2                      MIN  165 <--->                      MIN  665        CONN
  152       39.2                      MIN  219 ---->      PR251:  H2O + C29H19N3O3        CONN
  153       39.3                      MIN  300 ---->       PR17:  H2O + C29H19N3O3        CONN
  154       39.3                      MIN   45 <--->                      MIN  341        CONN
  155       39.3                      MIN  230 <--->                      MIN  391        CONN
  156       39.3                      MIN  244 <--->                      MIN  702        CONN
  157       39.5                      MIN  454 ---->      PR147:  H2O + C29H19N3O3        CONN
  158       39.5                      MIN  157 <--->                      MIN  341        CONN
  159       39.5                      MIN   65 <--->                      MIN  209        CONN
  160       39.6                      MIN  304 <--->                      MIN  292        CONN
  161       39.7                      MIN   70 ---->      PR305:  H2O + C29H19N3O3        CONN
  162       39.8                      MIN   19 <--->                      MIN  286        CONN
  164       39.8                      MIN  209 ---->      PR260:  H2O + C29H19N3O3        CONN
  165       39.9                      MIN  353 <--->                      MIN  203        CONN
  166       40.0                      MIN   97 <--->                      MIN  652        CONN
  167       40.1                      MIN  318 ---->      PR143:  H2O + C29H19N3O3        CONN
  169       40.2                      MIN    2 <--->                      MIN   27        CONN
  170       40.3                      MIN  600 <--->                      MIN  936        CONN
  171       40.8                      MIN  646 ---->       PR61:  H2O + C29H19N3O3        CONN
  172       40.9                      MIN  668 <--->                      MIN  834        CONN
  173       40.9                      MIN  121 ---->      PR274:  CO2 + C28H21N3O2     DISCONN
  174       41.0                      MIN  396 ---->       PR184:  CO + C28H21N3O3        CONN
  175       41.1                      MIN  219 <--->                      MIN  442        CONN
  177       41.2                      MIN    3 <--->                      MIN  454        CONN
  178       41.2                      MIN  116 <--->                      MIN  821        CONN
  179       41.4                      MIN   68 <--->                      MIN   90        CONN
  181       41.5                      MIN  219 <--->                      MIN  442        CONN
  183       41.5                      MIN  238 <--->                      MIN  203        CONN
  184       41.6                      MIN  116 ---->        PR4:  H2O + C29H19N3O3        CONN
  185       41.6                      MIN  219 <--->                      MIN  894        CONN
  186       41.6                      MIN    3 <--->                      MIN  807        CONN
  187       41.6                      MIN  646 ---->        PR71:  H2 + C29H19N3O4        CONN
  188       41.6                      MIN  116 ---->        PR4:  H2O + C29H19N3O3        CONN
  189       41.6                      MIN  231 <--->                      MIN  203        CONN
  190       41.7                      MIN  183 ---->      PR161:  H2O + C29H19N3O3        CONN
  191       42.0                      MIN  325 <--->                      MIN  976        CONN
  192       42.0                      MIN   68 <--->                      MIN   90        CONN
  193       42.0                      MIN  203 <--->                      MIN  834        CONN
  194       42.0                      MIN    3 <--->                      MIN  454        CONN
  195       42.1                      MIN    7 <--->                      MIN  341        CONN
  196       42.1                      MIN  219 <--->                      MIN  442        CONN
  197       42.1                      MIN  140 ---->      PR108:  H2O + C29H19N3O3        CONN
  198       42.2                      MIN  810 <--->                      MIN  970        CONN
  199       42.2                      MIN  116 ---->        PR4:  H2O + C29H19N3O3        CONN
  201       42.4                      MIN  353 <--->                      MIN  702        CONN
  202       42.5                      MIN   97 <--->                      MIN  179        CONN
  203       42.5                      MIN   45 <--->                      MIN  728        CONN
  204       42.5                      MIN  264 <--->                      MIN  203        CONN
  205       42.5                      MIN  799 <--->                      MIN  839        CONN
  206       42.6                      MIN  853 <--->                      MIN  939        CONN
  207       42.6                      MIN   97 <--->                      MIN  179        CONN
  208       42.6                      MIN  716 <--->                      MIN  702        CONN
  209       42.7                      MIN   81 ---->      PR302:  H2O + C29H19N3O3        CONN
  210       42.7                      MIN   61 <--->                      MIN  165        CONN
  211       42.8                      MIN  853 <--->                      MIN  939        CONN
  212       42.9                      MIN    3 <--->                      MIN   45        CONN
  213       43.1                      MIN    3 <--->                      MIN  341        CONN
  214       43.1                      MIN    3 <--->                      MIN   45        CONN
  215       43.3                      MIN  300 <--->                      MIN  599        CONN
  216       43.4                      MIN  125 <--->                      MIN  141        CONN
  217       43.4                      MIN  651 <--->                      MIN  951     DISCONN
  218       43.4                      MIN  203 <--->                      MIN  834        CONN
  219       43.5                      MIN  853 <--->                      MIN  939        CONN
  220       43.5                      MIN  423 <--->                      MIN  745        CONN
  221       43.5                      MIN  396 ---->        PR72:  CO + C28H21N3O3        CONN
  222       43.6                      MIN  688 <--->                      MIN  798        CONN
  223       43.6                      MIN  219 <--->                      MIN  442        CONN
  224       43.7                      MIN  219 ---->      PR229:  H2O + C29H19N3O3        CONN
  225       43.7                      MIN  853 <--->                      MIN  939        CONN
  226       43.8                      MIN  938 <--->                      MIN  967        CONN
  227       43.8                      MIN  116 ---->      PR1:  C9H4O3 + C20H17N3O        CONN
  228       44.1                      MIN  231 <--->                      MIN  868        CONN
  229       44.1                      MIN    7 <--->                      MIN   45        CONN
  230       44.2                      MIN  219 <--->                      MIN  566        CONN
  231       44.4                      MIN   70 <--->                      MIN  605        CONN
  233       44.6                      MIN  442 <--->                      MIN  936        CONN
  234       44.6                      MIN   71 <--->                      MIN   81        CONN
  235       44.7                      MIN  405 <--->                      MIN  562        CONN
  237       44.9                      MIN   70 <--->                      MIN  605        CONN
  238       44.9                      MIN  286 <--->                      MIN  417        CONN
  239       45.0                      MIN  498 <--->                      MIN  926        CONN
  241       45.2                      MIN  303 <--->                      MIN  646        CONN
  242       45.2                      MIN  751 <--->                      MIN  911        CONN
  243       45.3                      MIN  821 <--->                      MIN  851        CONN
  245       45.4                      MIN   58 <--->                      MIN  550        CONN
  246       45.4                      MIN   19 <--->                      MIN  405        CONN
  247       45.5                      MIN  673 ---->       PR245:  CO + C28H21N3O3        CONN
  248       45.6                      MIN  252 ---->    PR344:  CH2O2 + C28H19N3O2        CONN
  249       45.6                      MIN  331 <--->                      MIN  417        CONN
  250       45.6                      MIN  198 ---->      PR315:  H2O + C29H19N3O3        CONN
  251       45.7                      MIN  461 ---->       PR28:  H2O + C29H19N3O3        CONN
  252       45.7                      MIN  291 <--->                      MIN  938        CONN
  253       45.8                      MIN  264 <--->                      MIN  203        CONN
  254       46.0                      MIN  203 <--->                      MIN  353        CONN
  255       46.0                      MIN   68 ---->    PR110:  CH2O2 + C28H19N3O2        CONN
  256       46.1                      MIN  667 <--->                      MIN  702        CONN
  257       46.1                      MIN  264 <--->                      MIN  877        CONN
  258       46.1                      MIN   20 <--->                      MIN  448        CONN
  259       46.2                      MIN  625 <--->                      MIN  662     DISCONN
  260       46.3                      MIN  809 <--->                      MIN  875     DISCONN
  261       46.5                      MIN   20 <--->                      MIN  532        CONN
  262       46.5                      MIN   39 <--->                      MIN   71        CONN
  263       46.5                      MIN  264 <--->                      MIN  203        CONN
  264       46.6                      MIN   19 ---->       PR40:  H2O + C29H19N3O3        CONN
  265       46.8                      MIN   70 <--->                      MIN  190        CONN
  266       46.8                      MIN  974 ---->    PR91:  C8H6O2 + C21H15N3O2     DISCONN
  267       46.9                      MIN   28 <--->                      MIN  711        CONN
  268       47.0                      MIN   97 <--->                      MIN  466        CONN
  269       47.1                      MIN  116 <--->                      MIN  303        CONN
  270       47.1                      MIN  116 <--->                      MIN  303        CONN
  271       47.2                      MIN   70 <--->                      MIN  605        CONN
  272       47.3                      MIN  241 ---->       PR339:  CO + C28H21N3O3        CONN
  274       47.4                      MIN  338 ---->       PR295:  CO + C28H21N3O3        CONN
  275       47.5                      MIN  853 <--->                      MIN  939        CONN
  276       47.5                      MIN   39 <--->                      MIN   71        CONN
  277       48.1                      MIN  296 <--->                      MIN  633        CONN
  278       48.1                      MIN  688 <--->                      MIN 1006        CONN
  279       48.1                      MIN  791 <--->                      MIN  862        CONN
  280       48.2                      MIN  674 ---->    PR228:  CH2O2 + C28H19N3O2        CONN
  281       48.2                      MIN   20 <--->                      MIN  532        CONN
  282       48.2                      MIN   39 <--->                      MIN   67        CONN
  283       48.2                      MIN  141 <--->                      MIN  325        CONN
  284       48.3                      MIN  141 <--->                      MIN  636        CONN
  285       48.3                      MIN  203 <--->                      MIN  652        CONN
  286       48.3                      MIN    3 <--->                      MIN  807        CONN
  287       48.3                      MIN  807 ---->        PR95:  CO + C28H21N3O3        CONN
  288       48.4                      MIN  244 <--->                      MIN  353        CONN
  289       48.4                      MIN   19 <--->                      MIN  646        CONN
  290       48.5                      MIN  543 ---->      PR294:  H2O + C29H19N3O3     DISCONN
  292       48.5                      MIN  417 <--->                      MIN  853        CONN
  293       48.7                      MIN  699 <--->                      MIN  871     DISCONN
  294       48.7                      MIN   70 <--->                      MIN  605        CONN
  295       48.9                      MIN  600 <--->                      MIN  936        CONN
  296       48.9                      MIN  141 <--->                      MIN  636        CONN
  298       49.0                      MIN  468 ---->      PR237:  H2O + C29H19N3O3     DISCONN
  300       49.1                      MIN   19 <--->                      MIN  646        CONN
  301       49.1                      MIN  667 <--->                      MIN  753        CONN
  302       49.1                      MIN  244 <--->                      MIN  770        CONN
  303       49.1                      MIN    3 <--->                      MIN  539        CONN
  304       49.3                      MIN   26 <--->                      MIN  575        CONN
  305       49.3                      MIN  809 <--->                      MIN  875     DISCONN
  306       49.3                      MIN  141 <--->                      MIN  325        CONN
  307       49.6                      MIN  264 <--->                      MIN  203        CONN
  308       49.6                      MIN  325 ---->        PR95:  CO + C28H21N3O3        CONN
  309       49.8                      MIN  264 <--->                      MIN 1039        CONN
  310       49.8                      MIN  781 <--->                      MIN  875     DISCONN
  311       49.8                      MIN  407 <--->                      MIN  513        CONN
  312       49.8                      MIN  125 ---->       PR245:  CO + C28H21N3O3        CONN
  313       50.1                      MIN  766 <--->                      MIN  941        CONN
  314       50.1                      MIN  142 <--->                      MIN  333        CONN
  315       50.2                      MIN  917 <--->                      MIN  967        CONN
  316       50.2                      MIN   19 <--->                      MIN  646        CONN
  317       50.2                      MIN  141 <--->                      MIN  636        CONN
  318       50.2                      MIN  264 <--->                      MIN 1039        CONN
  319       50.3                      MIN  325 ---->        PR94:  CO + C28H21N3O3        CONN
  320       50.3                      MIN  658 <--->                      MIN  739     DISCONN
  321       50.3                      MIN  203 <--->                      MIN  626        CONN
  323       50.5                      MIN  587 <--->                      MIN  756     DISCONN
  324       50.6                      MIN  574 <--->                      MIN  442        CONN
  325       50.6                      MIN  141 <--->                      MIN  427        CONN
  326       50.7                      MIN   31 <--->                      MIN  359        CONN
  328       50.8                      MIN   59 <--->                      MIN  580     DISCONN
  329       50.9                      MIN  252 ---->  PR343:  CO + H2 + C28H19N3O3        CONN
  330       50.9                      MIN  141 <--->                      MIN  498        CONN
  331       51.0                      MIN  116 <--->                      MIN  711        CONN
  332       51.0                      MIN   65 <--->                      MIN  794        CONN
  333       51.1                      MIN  794 <--->                      MIN  862        CONN
  334       51.1                      MIN  862 <--->                      MIN 1071        CONN
  335       51.1                      MIN  696 <--->                      MIN  989        CONN
  336       51.1                      MIN  674 ---->    PR119:  CH2O2 + C28H19N3O2        CONN
  337       51.1                      MIN  198 <--->                      MIN   70        CONN
  338       51.1                      MIN  341 <--->                      MIN  330        CONN
  339       51.2                      MIN 1015 ---->    PR129:  CH2O2 + C28H19N3O2     DISCONN
  341       51.3                      MIN    2 ---->       PR117:  CO + C28H21N3O3        CONN
  342       51.4                      MIN   27 <--->                      MIN  512        CONN
  343       51.4                      MIN  355 <--->                      MIN  368        CONN
  344       51.4                      MIN  325 ---->        PR62:  CO + C28H21N3O3        CONN
  345       51.6                      MIN  456 <--->                      MIN  794        CONN
  346       51.6                      MIN   81 <--->                      MIN  355        CONN
  347       51.7                      MIN   26 ---->       PR381:  CO + C28H21N3O3        CONN
  348       51.7                      MIN  268 ---->       PR301:  CO + C28H21N3O3        CONN
  350       51.8                      MIN  244 ---->   PR348:  C8H4O2 + C21H17N3O2        CONN
  351       51.9                      MIN  602 <--->                      MIN  810        CONN
  352       51.9                      MIN    7 <--->                      MIN  142        CONN
  353       51.9                      MIN   19 <--->                      MIN  513        CONN
  356       52.0                      MIN  396 <--->                      MIN  719        CONN
  357       52.2                      MIN  219 <--->                      MIN  854        CONN
  358       52.2                      MIN  602 <--->                      MIN  824        CONN
  359       52.2                      MIN   96 <--->                      MIN  673        CONN
  360       52.2                      MIN  165 <--->                      MIN  264        CONN
  361       52.2                      MIN  206 <--->                      MIN  658     DISCONN
  362       52.3                      MIN   58 <--->                      MIN  510        CONN
  364       52.4                      MIN  129 <--->                      MIN  937        CONN
  365       52.5                      MIN  182 <--->                      MIN  987     DISCONN
  366       52.5                      MIN  518 ---->     PR15:  C8H6O3 + C21H15N3O     DISCONN
  368       52.6                      MIN   96 <--->                      MIN  359        CONN
  369       52.6                      MIN  142 <--->                      MIN  333        CONN
  370       52.7                      MIN  150 <--->                      MIN  178        CONN
  371       52.7                      MIN   96 <--->                      MIN  591        CONN
  372       52.9                      MIN  674 ---->    PR129:  CH2O2 + C28H19N3O2        CONN
  373       52.9                      MIN    2 <--->                      MIN   19        CONN
  374       53.0                      MIN  599 <--->                      MIN  532        CONN
  375       53.0                      MIN    2 <--->                      MIN   19        CONN
  376       53.0                      MIN  209 <--->                      MIN  965        CONN
  377       53.0                      MIN  777 ---->    PR273:  CH2O2 + C28H19N3O2     DISCONN
  379       53.2                      MIN   58 <--->                      MIN  673        CONN
  380       53.3                      MIN    3 <--->                      MIN  148        CONN
  383       53.6                      MIN   71 <--->                      MIN  203        CONN
  384       53.6                      MIN  391 <--->                      MIN 1010        CONN
  385       53.6                      MIN   31 <--->                      MIN  673        CONN
  386       53.7                      MIN  116 <--->                      MIN  711        CONN
  387       53.7                      MIN  673 <--->                      MIN  988        CONN
  388       53.7                      MIN  353 <--->                      MIN  854        CONN
  389       53.7                      MIN  141 <--->                      MIN  498        CONN
  391       53.9                      MIN  303 <--->                      MIN  907        CONN
  392       54.0                      MIN  264 ---->    PR123:  CH2O2 + C28H19N3O2        CONN
  394       54.0                      MIN  775 ---->      PR175:  CO2 + C28H21N3O2     DISCONN
  395       54.1                      MIN  442 <--->                      MIN 1035        CONN
  397       54.2                      MIN    7 ---->       PR115:  CO + C28H21N3O3        CONN
  398       54.2                      MIN  782 <--->                      MIN  791        CONN
  399       54.3                      MIN   19 <--->                      MIN  513        CONN
  400       54.4                      MIN  463 <--->                      MIN  983        CONN
  401       54.4                      MIN    3 ---->       PR199:  CO + C28H21N3O3        CONN
  402       54.5                      MIN  209 <--->                      MIN  965        CONN
  403       54.5                      MIN  674 ---->    PR129:  CH2O2 + C28H19N3O2        CONN
  404       54.6                      MIN 1025 <--->                      MIN 1106     DISCONN
  405       54.9                      MIN  878 ---->     PR85:  C8H6O3 + C21H15N3O        CONN
  406       54.9                      MIN   68 <--->                      MIN  959        CONN
  407       54.9                      MIN  697 <--->                      MIN  904     DISCONN
  408       54.9                      MIN   68 <--->                      MIN  959        CONN
  409       54.9                      MIN    3 ---->       PR139:  CO + C28H21N3O3        CONN
  410       55.0                      MIN  652 ---->       PR309:  CO + C28H21N3O3        CONN
  411       55.1                      MIN   19 <--->                      MIN 1103        CONN
  412       55.1                      MIN  166 <--->                      MIN  341        CONN
  415       55.3                      MIN  696 <--->                      MIN  986        CONN
  416       55.3                      MIN   96 <--->                      MIN  695        CONN
  417       55.4                      MIN   26 <--->                      MIN  307        CONN
  419       55.7                      MIN   31 <--->                      MIN  878        CONN
  420       55.7                      MIN  980 ---->      PR356:  H2O + C29H19N3O3     DISCONN
  421       55.8                      MIN  325 ---->        PR62:  CO + C28H21N3O3        CONN
  422       55.8                      MIN  264 <--->                      MIN 1039        CONN
  423       55.9                      MIN   71 <--->                      MIN  203        CONN
  425       56.0                      MIN  456 <--->                      MIN  794        CONN
  426       56.0                      MIN  747 <--->                      MIN  906     DISCONN
  427       56.0                      MIN  338 <--->                      MIN  782        CONN
  428       56.1                      MIN   19 <--->                      MIN   27        CONN
  429       56.1                      MIN  116 <--->                      MIN  141        CONN
  430       56.1                      MIN  391 <--->                      MIN  705        CONN
  431       56.3                      MIN  243 <--->                      MIN 1065     DISCONN
  432       56.3                      MIN   58 <--->                      MIN  510        CONN
  433       56.3                      MIN   68 <--->                      MIN  763        CONN
  435       56.4                      MIN   67 <--->                      MIN  203        CONN
  436       56.4                      MIN  667 <--->                      MIN  753        CONN
  437       56.6                      MIN  562 ---->     PR97:  CH2O2 + C28H19N3O2        CONN
  438       56.8                      MIN 1045 ---->       PR52:  H2O + C29H19N3O3     DISCONN
  439       56.8                      MIN   26 <--->                      MIN  307        CONN
  440       56.9                      MIN   68 ---->    PR110:  CH2O2 + C28H19N3O2        CONN
  441       56.9                      MIN   90 <--->                      MIN  918        CONN
  442       57.1                      MIN  608 ----> PR346:  CO + H2O + C28H19N3O2        CONN
  443       57.1                      MIN  179 ---->    PR366:  CH2O2 + C28H19N3O2        CONN
  444       57.2                      MIN  303 <--->                      MIN  407        CONN
  445       57.3                      MIN  244 ---->       PR275:  CO + C28H21N3O3        CONN
  446       57.5                      MIN    2 <--->                      MIN 1093        CONN
  447       57.6                      MIN  286 <--->                      MIN  959        CONN
  448       57.6                      MIN  656 <--->                      MIN 1043     DISCONN
  449       57.6                      MIN  491 <--->                      MIN 1050     DISCONN
  451       57.6                      MIN   97 <--->                      MIN  485        CONN
  452       57.7                      MIN  286 <--->                      MIN  930        CONN
  454       57.7                      MIN  943 ---->    PR172:  CH2O2 + C28H19N3O2     DISCONN
  455       57.8                      MIN  911 <--->                      MIN  938        CONN
  456       57.8                      MIN  695 <--->                      MIN  967        CONN
  457       57.9                      MIN  341 <--->                      MIN 1070        CONN
  458       57.9                      MIN  396 ----> PR196:  CO + H2O + C28H19N3O2        CONN
  459       57.9                      MIN  471 ---->       PR182:  CO + C28H21N3O3        CONN
  460       57.9                      MIN  407 <--->                      MIN  303        CONN
  461       57.9                      MIN  338 <--->                      MIN  519        CONN
  462       58.0                      MIN  171 ---->      PR112:  H2O + C29H19N3O3     DISCONN
  463       58.0                      MIN  264 ---->      PR260:  H2O + C29H19N3O3        CONN
  464       58.0                      MIN   67 <--->                      MIN  203        CONN
  465       58.0                      MIN  702 ---->       PR275:  CO + C28H21N3O3        CONN
  466       58.0                      MIN   68 <--->                      MIN  396        CONN
  467       58.1                      MIN   27 <--->                      MIN   19        CONN
  468       58.2                      MIN  244 <--->                      MIN  650        CONN
  469       58.4                      MIN    3 <--->                      MIN  892        CONN
  470       58.5                      MIN   45 ---->    PR122:  CH2O2 + C28H19N3O2        CONN
  471       58.5                      MIN  691 <--->                      MIN  711        CONN
  473       58.6                      MIN   90 <--->                      MIN  396        CONN
  474       58.7                      MIN  370 <--->                      MIN  442        CONN
  475       58.8                      MIN  618 <--->                      MIN 1112        CONN
  476       58.8                      MIN  264 <--->                      MIN  434        CONN
  477       58.9                      MIN  423 <--->                      MIN  512        CONN
  478       58.9                      MIN  488 <--->                      MIN 1077     DISCONN
  479       58.9                      MIN    7 ---->    PR110:  CH2O2 + C28H19N3O2        CONN
  481       59.0                      MIN  519 <--->                      MIN  779        CONN
  482       59.2                      MIN   65 ---->      PR265:  H2O + C29H19N3O3        CONN
  483       59.2                      MIN    7 ---->    PR110:  CH2O2 + C28H19N3O2        CONN
  484       59.4                      MIN  330 <--->                      MIN  863        CONN
  485       59.5                      MIN  203 ---->      PR357:  H2O + C29H19N3O3        CONN
  486       59.6                      MIN  765 <--->                      MIN 1007     DISCONN
  488       59.7                      MIN  209 <--->                      MIN  965        CONN
  489       59.7                      MIN 1066 ---->       PR319:  CO + C28H21N3O3     DISCONN
  490       59.7                      MIN  353 ---->      PR368:  H2O + C29H19N3O3        CONN
  492       59.8                      MIN  519 ---->    PR291:  CH2O2 + C28H19N3O2        CONN
  493       59.8                      MIN  166 <--->                      MIN 1074        CONN
  494       59.9                      MIN  219 <--->                      MIN  936        CONN
  496       60.0                      MIN  512 ---->      PR147:  H2O + C29H19N3O3        CONN
  497       60.1                      MIN  286 ---->        PR72:  CO + C28H21N3O3        CONN
  498       60.1                      MIN  877 ----> PR127:  CO + H2O + C28H19N3O2        CONN
  499       60.1                      MIN   27 <--->                      MIN   19        CONN
  500       60.2                      MIN  238 <--->                      MIN   81        CONN
  501       60.3                      MIN  142 <--->                      MIN 1072        CONN
  502       60.4                      MIN  604 <--->                      MIN 1147     DISCONN
  503       60.4                      MIN  203 <--->                      MIN  353        CONN
  504       60.4                      MIN  268 ---->       PR359:  H2 + C29H19N3O4        CONN
  506       60.5                      MIN  268 <--->                      MIN  523        CONN
  507       60.5                      MIN   19 <--->                      MIN  939        CONN
  508       60.6                      MIN  407 ---->     PR84:  C8H6O3 + C21H15N3O        CONN
  509       60.7                      MIN   96 <--->                      MIN  591        CONN
  510       60.8                      MIN  811 <--->                      MIN 1045     DISCONN
  511       60.8                      MIN   26 <--->                      MIN  702        CONN
  512       60.8                      MIN  407 ---->     PR84:  C8H6O3 + C21H15N3O        CONN
  513       60.8                      MIN  485 <--->                      MIN   96        CONN
  514       60.8                      MIN  325 <--->                      MIN  709        CONN
  515       61.0                      MIN   70 ---->    PR306:  CH2O2 + C28H19N3O2        CONN
  516       61.0                      MIN  456 ---->      PR296:  CO2 + C28H21N3O2        CONN
  517       61.1                      MIN   19 <--->                      MIN  513        CONN
  518       61.2                      MIN    3 ---->    PR110:  CH2O2 + C28H19N3O2        CONN
  519       61.3                      MIN  294 <--->                      MIN  523        CONN
  520       61.4                      MIN  353 ---->      PR368:  H2O + C29H19N3O3        CONN
  521       61.4                      MIN  264 ---->      PR292:  H2O + C29H19N3O3        CONN
  522       61.4                      MIN    7 <--->                      MIN    2        CONN
  523       61.4                      MIN  273 <--->                      MIN 1136     DISCONN
  524       61.4                      MIN  117 <--->                      MIN  513        CONN
  527       61.6                      MIN  286 <--->                      MIN  930        CONN
  528       61.7                      MIN  396 ---->    PR214:  CH2O2 + C28H19N3O2        CONN
  529       61.8                      MIN  244 <--->                      MIN  650        CONN
  530       61.8                      MIN  942 <--->                      MIN 1062     DISCONN
  531       61.8                      MIN  696 ---->     PR92:  C8H6O3 + C21H15N3O        CONN
  532       61.9                      MIN  165 <--->                      MIN  209        CONN
  533       61.9                      MIN   27 <--->                      MIN  300        CONN
  534       61.9                      MIN  463 <--->                      MIN  725        CONN
  535       61.9                      MIN  442 ---->    PR235:  C9H4O3 + C20H17N3O        CONN
  536       61.9                      MIN    2 <--->                      MIN  117        CONN
  537       62.0                      MIN  140 ---->      PR101:  CO2 + C28H21N3O2        CONN
  538       62.1                      MIN  286 <--->                      MIN  930        CONN
  539       62.2                      MIN  268 <--->                      MIN  519        CONN
  540       62.2                      MIN   26 <--->                      MIN  702        CONN
  541       62.2                      MIN  252 <--->                      MIN  650        CONN
  542       62.3                      MIN    7 <--->                      MIN  396        CONN
  543       62.4                      MIN  103 ---->       PR295:  CO + C28H21N3O3        CONN
  544       62.4                      MIN  116 <--->                      MIN  682        CONN
  545       62.6                      MIN  268 <--->                      MIN  523        CONN
  546       62.6                      MIN    2 <--->                      MIN  117        CONN
  547       62.6                      MIN  331 <--->                      MIN 1011        CONN
  548       62.7                      MIN  116 <--->                      MIN  682        CONN
  549       62.7                      MIN  252 <--->                      MIN  650        CONN
  550       62.7                      MIN  461 <--->                      MIN  967        CONN
  551       62.7                      MIN    7 <--->                      MIN  396        CONN
  552       62.8                      MIN  463 <--->                      MIN  725        CONN
  553       62.8                      MIN  135 <--->                      MIN  977        CONN
  554       62.8                      MIN  231 ---->       PR288:  H2 + C29H19N3O4        CONN
  555       62.8                      MIN   97 ---->   PR347:  C8H4O2 + C21H17N3O2        CONN
  556       62.8                      MIN  407 ---->     PR85:  C8H6O3 + C21H15N3O        CONN
  557       62.9                      MIN   27 <--->                      MIN  513        CONN
  558       62.9                      MIN  692 ---->      PR147:  H2O + C29H19N3O3     DISCONN
  559       62.9                      MIN   20 <--->                      MIN  576        CONN
  561       63.2                      MIN   58 ---->       PR339:  CO + C28H21N3O3        CONN
  562       63.3                      MIN  338 <--->                      MIN  782        CONN
  563       63.3                      MIN  125 <--->                      MIN  597        CONN
  565       63.4                      MIN  264 ---->      PR280:  CO2 + C28H21N3O2        CONN
  566       63.4                      MIN  736 <--->                      MIN  728        CONN
  567       63.4                      MIN  656 ---->        PR88:  CO + C28H21N3O3     DISCONN
  568       63.5                      MIN   31 <--->                      MIN 1150        CONN
  570       63.6                      MIN   70 ---->    PR306:  CH2O2 + C28H19N3O2        CONN
  571       63.6                      MIN  391 ---->      PR79:  CH2O + C28H19N3O3        CONN
  572       63.6                      MIN  407 ---->     PR84:  C8H6O3 + C21H15N3O        CONN
  573       63.6                      MIN   27 <--->                      MIN   19        CONN
  574       63.7                      MIN    7 <--->                      MIN  618        CONN
  575       63.7                      MIN  997 ---->       PR183:  CO + C28H21N3O3        CONN
  576       63.7                      MIN   27 <--->                      MIN   45        CONN
  577       63.8                      MIN  116 <--->                      MIN  141        CONN
  578       63.9                      MIN   26 <--->                      MIN   20        CONN
  579       64.0                      MIN   45 <--->                      MIN  175        CONN
  580       64.0                      MIN   90 <--->                      MIN  396        CONN
  581       64.0                      MIN    3 <--->                      MIN  396        CONN
  582       64.0                      MIN  330 <--->                      MIN  863        CONN
  583       64.0                      MIN  230 <--->                      MIN 1067        CONN
  584       64.1                      MIN  230 <--->                      MIN  766        CONN
  585       64.1                      MIN  179 <--->                      MIN  523        CONN
  586       64.1                      MIN    2 <--->                      MIN    7        CONN
  588       64.5                      MIN  844 <--->                      MIN 1018     DISCONN
  589       64.6                      MIN    3 <--->                      MIN 1001        CONN
  590       64.6                      MIN   45 <--->                      MIN  380        CONN
  591       64.6                      MIN  372 ---->        PR13:  CO + C28H21N3O3        CONN
  592       64.7                      MIN  624 <--->                      MIN 1002     DISCONN
  593       64.8                      MIN   27 <--->                      MIN   45        CONN
  594       64.8                      MIN  209 <--->                      MIN 1107        CONN
  595       64.8                      MIN  950 <--->                      MIN 1068     DISCONN
  597       64.9                      MIN  391 ---->       PR27:  H2O + C29H19N3O3        CONN
  598       64.9                      MIN   46 <--->                      MIN  183        CONN
  599       65.0                      MIN  417 ---->      PR86:  CH2O + C28H19N3O3        CONN
  600       65.0                      MIN  470 <--->                      MIN  656     DISCONN
  601       65.0                      MIN   26 <--->                      MIN  702        CONN
  602       65.2                      MIN   96 <--->                      MIN  770        CONN
  604       65.2                      MIN  950 <--->                      MIN 1068     DISCONN
  605       65.2                      MIN   19 ---->        PR48:  H2 + C29H19N3O4        CONN
  606       65.2                      MIN 1083 ---->       PR389:  CO + C28H21N3O3        CONN
  607       65.3                      MIN  471 ---->     PR192:  CH2O + C28H19N3O3        CONN
  608       65.3                      MIN  365 <--->                      MIN  576        CONN
  609       65.5                      MIN  252 <--->                      MIN  608        CONN
  610       65.5                      MIN  353 <--->                      MIN  556        CONN
  611       65.5                      MIN  702 <--->                      MIN 1084        CONN
  613       65.7                      MIN  292 <--->                      MIN  498        CONN
  615       65.8                      MIN  835 ---->    PR68:  C8H4O2 + C21H17N3O2     DISCONN
  617       66.0                      MIN   59 ---->   PR340:  C8H4O2 + C21H17N3O2     DISCONN
  618       66.0                      MIN  175 ---->        PR38:  CO + C28H21N3O3        CONN
  619       66.1                      MIN  203 <--->                      MIN  846        CONN
  620       66.1                      MIN   19 <--->                      MIN  513        CONN
  622       66.2                      MIN   81 <--->                      MIN  523        CONN
  623       66.2                      MIN  528 <--->                      MIN 1102     DISCONN
  624       66.2                      MIN  325 <--->                      MIN  709        CONN
  627       66.3                      MIN   19 ---->        PR48:  H2 + C29H19N3O4        CONN
  629       66.4                      MIN  825 ---->    PR105:  CH2O2 + C28H19N3O2     DISCONN
  630       66.5                      MIN  140 <--->                      MIN  975        CONN
  631       66.5                      MIN   59 <--->                      MIN  915     DISCONN
  632       66.7                      MIN  252 <--->                      MIN  608        CONN
  633       66.7                      MIN  219 ---->    PR248:  CH2O2 + C28H19N3O2        CONN
  634       66.7                      MIN  116 ---->   PR337:  C8H4O2 + C21H17N3O2        CONN
  635       66.9                      MIN   20 ---->   PR386:  C8H4O2 + C21H17N3O2        CONN
  636       67.0                      MIN  796 ---->      PR86:  CH2O + C28H19N3O3     DISCONN
  637       67.0                      MIN   97 <--->                      MIN 1083        CONN
  638       67.1                      MIN 1009 <--->                      MIN 1077     DISCONN
  639       67.1                      MIN 1026 ---->    PR181:  C8H6O3 + C21H15N3O     DISCONN
  641       67.1                      MIN   96 <--->                      MIN 1160        CONN
  642       67.1                      MIN  405 <--->                      MIN  423        CONN
  643       67.2                      MIN   96 ---->   PR330:  C8H4O2 + C21H17N3O2        CONN
  644       67.3                      MIN   26 <--->                      MIN  353        CONN
  648       67.3                      MIN  375 <--->                      MIN 1005        CONN
  649       67.4                      MIN  140 ---->     PR99:  CH2O2 + C28H19N3O2        CONN
  650       67.5                      MIN  807 <--->                      MIN 1134        CONN
  651       67.5                      MIN   81 <--->                      MIN   89        CONN
  652       67.8                      MIN  300 <--->                      MIN 1040        CONN
  653       67.8                      MIN  805 <--->                      MIN  910        CONN
  655       67.9                      MIN  219 ---->    PR244:  CH2O2 + C28H19N3O2        CONN
  657       68.1                      MIN  918 <--->                      MIN 1038        CONN
  658       68.1                      MIN  375 <--->                      MIN  405        CONN
  659       68.2                      MIN  129 ---->     PR15:  C8H6O3 + C21H15N3O        CONN
  660       68.2                      MIN  296 <--->                      MIN  768        CONN
  662       68.3                      MIN  179 <--->                      MIN  556        CONN
  663       68.3                      MIN  405 <--->                      MIN  423        CONN
  664       68.4                      MIN  380 <--->                      MIN  442        CONN
  665       68.4                      MIN  286 ---->        PR72:  CO + C28H21N3O3        CONN
  666       68.5                      MIN   46 <--->                      MIN  150        CONN
  667       68.5                      MIN  375 <--->                      MIN  512        CONN
  668       68.6                      MIN  811 ---->        PR9:  H2O + C29H19N3O3     DISCONN
  669       68.6                      MIN  375 <--->                      MIN 1166        CONN
  670       68.7                      MIN  140 ---->     PR98:  CH2O2 + C28H19N3O2        CONN
  671       68.7                      MIN  917 ---->    PR35:  C8H4O2 + C21H17N3O2        CONN
  672       68.8                      MIN  230 <--->                      MIN  725        CONN
  673       68.9                      MIN  264 <--->                      MIN  519        CONN
  674       68.9                      MIN  150 ---->       PR171:  CO + C28H21N3O3        CONN
  675       69.0                      MIN  116 <--->                      MIN  391        CONN
  676       69.0                      MIN   90 <--->                      MIN 1130        CONN
  678       69.1                      MIN  811 ---->        PR9:  H2O + C29H19N3O3     DISCONN
  679       69.1                      MIN  893 <--->                      MIN  971     DISCONN
  680       69.1                      MIN  882 <--->                      MIN 1129     DISCONN
  682       69.2                      MIN  650 ---->     PR312:  CH2O + C28H19N3O3        CONN
  683       69.3                      MIN  238 <--->                      MIN  203        CONN
  684       69.4                      MIN  230 <--->                      MIN  858        CONN
  685       69.5                      MIN  203 ---->       PR295:  CO + C28H21N3O3        CONN
  686       69.6                      MIN  142 <--->                      MIN 1173        CONN
  687       69.7                      MIN   96 <--->                      MIN  296        CONN
  688       69.7                      MIN 1162 ---->    PR132:  CH2O2 + C28H19N3O2     DISCONN
  689       69.9                      MIN  219 ---->    PR232:  CH2O2 + C28H19N3O2        CONN
  690       69.9                      MIN   27 ---->       PR37:  H2O + C29H19N3O3        CONN
  691       69.9                      MIN  209 <--->                      MIN  219        CONN
  692       69.9                      MIN  485 <--->                      MIN  910        CONN
  694       70.2                      MIN  117 <--->                      MIN 1143        CONN
  695       70.2                      MIN   27 ---->       PR37:  H2O + C29H19N3O3        CONN
  698       70.4                      MIN   20 <--->                      MIN  579        CONN
  699       70.4                      MIN 1135 ---->        PR36:  CO + C28H21N3O3     DISCONN
  701       70.4                      MIN  142 <--->                      MIN  675        CONN
  702       70.5                      MIN   97 ---->   PR349:  C8H4O2 + C21H17N3O2        CONN
  703       70.5                      MIN  405 <--->                      MIN  423        CONN
  704       70.5                      MIN  370 ---->       PR107:  CO + C28H21N3O3        CONN
  705       70.5                      MIN  292 <--->                      MIN 1158        CONN
  706       70.6                      MIN   59 ---->   PR335:  C8H4O2 + C21H17N3O2     DISCONN
  707       70.7                      MIN   96 ---->   PR387:  C8H4O2 + C21H17N3O2        CONN
  709       70.7                      MIN    3 <--->                      MIN  396        CONN
  710       70.9                      MIN  400 <--->                      MIN  555     DISCONN
  711       71.0                      MIN  258 <--->                      MIN 1088        CONN
  712       71.1                      MIN  103 ---->       PR268:  CO + C28H21N3O3        CONN
  713       71.2                      MIN  391 <--->                      MIN  696        CONN
  714       71.2                      MIN   40 ---->       PR159:  CO + C28H21N3O3        CONN
  715       71.3                      MIN   20 ---->   PR347:  C8H4O2 + C21H17N3O2        CONN
  716       71.3                      MIN   26 ---->       PR374:  H2 + C29H19N3O4        CONN
  717       71.3                      MIN   26 <--->                      MIN 1155        CONN
  718       71.4                      MIN 1096 ---->      PR86:  CH2O + C28H19N3O3     DISCONN
  719       71.5                      MIN    3 <--->                      MIN 1048        CONN
  721       71.6                      MIN  230 <--->                      MIN 1122        CONN
  722       71.6                      MIN  286 <--->                      MIN 1057        CONN
  724       72.1                      MIN   28 ---->        PR76:  H2 + C29H19N3O4        CONN
  725       72.2                      MIN   71 <--->                      MIN  203        CONN
  726       72.2                      MIN   27 <--->                      MIN   19        CONN
  727       72.3                      MIN   90 <--->                      MIN 1165        CONN
  728       72.4                      MIN   58 ---->   PR335:  C8H4O2 + C21H17N3O2        CONN
  729       72.5                      MIN   65 <--->                      MIN  965        CONN
  730       72.6                      MIN   31 ---->   PR334:  C8H4O2 + C21H17N3O2        CONN
  731       72.6                      MIN  554 <--->                      MIN  772        CONN
  732       72.7                      MIN  898 ---->       PR250:  CO + C28H21N3O3     DISCONN
  733       72.8                      MIN  423 <--->                      MIN  997        CONN
  734       72.8                      MIN  140 <--->                      MIN  375        CONN
  735       72.8                      MIN  264 <--->                      MIN  519        CONN
  736       72.8                      MIN  106 <--->                      MIN  901     DISCONN
  737       72.9                      MIN  150 <--->                      MIN  602        CONN
  738       73.1                      MIN   68 <--->                      MIN 1165        CONN
  740       73.1                      MIN  243 <--->                      MIN  829     DISCONN
  741       73.1                      MIN   26 ---->       PR377:  H2 + C29H19N3O4        CONN
  742       73.2                      MIN  258 <--->                      MIN  948        CONN
  743       73.4                      MIN  370 <--->                      MIN 1120        CONN
  744       73.5                      MIN  244 <--->                      MIN  923        CONN
  745       73.5                      MIN  456 ---->      PR297:  CO2 + C28H21N3O2        CONN
  746       73.6                      MIN  533 <--->                      MIN  876     DISCONN
  747       73.7                      MIN  582 <--->                      MIN 1127     DISCONN
  748       73.8                      MIN  219 <--->                      MIN  496        CONN
  750       73.9                      MIN  330 <--->                      MIN  741        CONN
  751       74.0                      MIN   40 ---->       PR158:  CO + C28H21N3O3        CONN
  752       74.0                      MIN   96 <--->                      MIN  296        CONN
  755       74.3                      MIN  811 ---->        PR9:  H2O + C29H19N3O3     DISCONN
  756       74.4                      MIN   20 <--->                      MIN  637        CONN
  757       74.5                      MIN  375 <--->                      MIN 1005        CONN
  759       74.8                      MIN  231 ---->       PR364:  H2 + C29H19N3O4        CONN
  760       74.9                      MIN  318 <--->                      MIN 1085        CONN
  761       74.9                      MIN  533 <--->                      MIN  876     DISCONN
  762       75.0                      MIN  754 ---->      PR278:  CO2 + C28H21N3O2     DISCONN
  763       75.0                      MIN  536 <--->                      MIN  741        CONN
  764       75.1                      MIN   71 <--->                      MIN 1117        CONN
  765       75.1                      MIN 1056 <--->                      MIN  967        CONN
  766       75.2                      MIN 1090 ---->       PR318:  CO + C28H21N3O3     DISCONN
  767       75.3                      MIN   59 <--->                      MIN  914     DISCONN
  768       75.4                      MIN  632 ---->       PR384:  CO + C28H21N3O3     DISCONN
  769       75.7                      MIN  318 <--->                      MIN 1073        CONN
  770       75.8                      MIN  513 <--->                      MIN 1156        CONN
  771       75.8                      MIN  330 <--->                      MIN  741        CONN
  772       76.0                      MIN  142 <--->                      MIN  992        CONN
  773       76.0                      MIN  268 ---->      PR360:  CO2 + C28H21N3O2        CONN
  774       76.1                      MIN   68 ---->      PR187:  CO2 + C28H21N3O2        CONN
  775       76.3                      MIN  417 <--->                      MIN 1088        CONN
  776       76.3                      MIN   40 <--->                      MIN  602        CONN
  779       76.5                      MIN  391 ---->        PR75:  H2 + C29H19N3O4        CONN
  780       76.6                      MIN  873 ---->       PR109:  CO + C28H21N3O3     DISCONN
  781       76.6                      MIN 1214 ---->       PR314:  CO + C28H21N3O3     DISCONN
  783       76.8                      MIN  264 ---->       PR290:  H2 + C29H19N3O4        CONN
  786       77.1                      MIN  370 ---->        PR96:  CO + C28H21N3O3        CONN
  787       77.1                      MIN   71 <--->                      MIN  676        CONN
  788       77.2                      MIN  427 <--->                      MIN  917        CONN
  789       77.2                      MIN  166 ---->       PR180:  CO + C28H21N3O3        CONN
  790       77.3                      MIN  936 <--->                      MIN 1188        CONN
  791       77.6                      MIN   68 ---->      PR187:  CO2 + C28H21N3O2        CONN
  792       77.7                      MIN  591 <--->                      MIN 1157        CONN
  793       77.7                      MIN   96 ---->   PR329:  C8H4O2 + C21H17N3O2        CONN
  794       77.7                      MIN  198 ---->    PR317:  CH2O2 + C28H19N3O2        CONN
  797       78.0                      MIN   40 ---->       PR158:  CO + C28H21N3O3        CONN
  798       78.1                      MIN    1 <--->                      MIN 1069     DISCONN
  799       78.2                      MIN  742 ---->        PR87:  CO + C28H21N3O3     DISCONN
  800       78.2                      MIN  417 <--->                      MIN  948        CONN
  801       78.2                      MIN  529 <--->                      MIN  636        CONN
  802       78.3                      MIN   46 <--->                      MIN  602        CONN
  804       78.5                      MIN  427 <--->                      MIN  880        CONN
  805       78.6                      MIN  742 ---->        PR87:  CO + C28H21N3O3     DISCONN
  807       78.7                      MIN 1097 <--->                      MIN 1156        CONN
  809       78.8                      MIN  864 <--->                      MIN 1187     DISCONN
  810       78.8                      MIN  603 <--->                      MIN  887        CONN
  811       78.9                      MIN  142 <--->                      MIN  423        CONN
  812       79.1                      MIN 1052 <--->                      MIN 1224     DISCONN
  813       79.3                      MIN  116 ---->         PR7:  H2 + C29H19N3O4        CONN
  814       79.3                      MIN  995 ---->    PR168:  CH2O2 + C28H19N3O2     DISCONN
  815       79.3                      MIN  215 ---->       PR176:  CO + C28H21N3O3        CONN
  816       79.3                      MIN  993 ---->      PR370:  H2O + C29H19N3O3     DISCONN
  817       79.4                      MIN 1044 ---->       PR269:  CO + C28H21N3O3     DISCONN
  818       79.5                      MIN   45 <--->                      MIN 1073        CONN
  819       79.7                      MIN  166 ---->       PR179:  CO + C28H21N3O3        CONN
  821       80.1                      MIN  300 <--->                      MIN  391        CONN
  823       80.3                      MIN  370 <--->                      MIN 1120        CONN
  824       80.4                      MIN  455 <--->                      MIN 1016     DISCONN
  825       80.4                      MIN   81 <--->                      MIN  990        CONN
  826       80.4                      MIN  116 <--->                      MIN  603        CONN
  827       80.4                      MIN  608 <--->                      MIN 1113        CONN
  828       80.4                      MIN  142 ---->    PR104:  CH2O2 + C28H19N3O2        CONN
  829       80.6                      MIN 1008 ---->     PR63:  C9H4O3 + C20H17N3O     DISCONN
  830       80.7                      MIN  252 ---->     PR345:  CH2O + C28H19N3O3        CONN
  831       80.8                      MIN  391 <--->                      MIN  696        CONN
  832       80.8                      MIN  934 <--->                      MIN 1061     DISCONN
  833       80.8                      MIN   19 <--->                      MIN  417        CONN
  834       80.9                      MIN 1162 ---->    PR283:  CH2O2 + C28H19N3O2     DISCONN
  836       81.2                      MIN 1151 ---->    PR110:  CH2O2 + C28H19N3O2     DISCONN
  837       81.2                      MIN 1028 <--->                      MIN 1054     DISCONN
  838       81.2                      MIN  927 <--->                      MIN 1087        CONN
  839       81.4                      MIN 1075 ---->      PR106:  CO2 + C28H21N3O2     DISCONN
  840       81.4                      MIN 1174 ---->   PR204:  C8H4O2 + C21H17N3O2     DISCONN
  841       81.5                      MIN  608 <--->                      MIN  856        CONN
  842       81.5                      MIN   81 <--->                      MIN 1017        CONN
  844       81.6                      MIN  646 <--->                      MIN 1212        CONN
  845       81.7                      MIN  775 <--->                      MIN 1121     DISCONN
  846       81.7                      MIN 1143 <--->                      MIN 1178        CONN
  847       81.7                      MIN  106 <--->                      MIN 1080     DISCONN
  848       81.7                      MIN    2 <--->                      MIN 1156        CONN
  850       82.0                      MIN  179 <--->                      MIN  523        CONN
  851       82.1                      MIN  498 <--->                      MIN 1182        CONN
  852       82.3                      MIN   40 ---->       PR158:  CO + C28H21N3O3        CONN
  853       82.3                      MIN  572 ---->    PR123:  CH2O2 + C28H19N3O2     DISCONN
  855       82.7                      MIN   40 <--->                      MIN  602        CONN
  856       82.8                      MIN  197 <--->                      MIN  848     DISCONN
  857       82.9                      MIN  512 <--->                      MIN 1005        CONN
  859       83.3                      MIN  702 <--->                      MIN 1197        CONN
  860       83.3                      MIN  179 <--->                      MIN 1034        CONN
  862       83.4                      MIN   81 <--->                      MIN  638        CONN
  864       84.5                      MIN  157 <--->                      MIN  646        CONN
  865       84.7                      MIN  246 <--->                      MIN 1031     DISCONN
  866       84.9                      MIN  770 ---->      PR332:  H2O + C29H19N3O3        CONN
  867       85.0                      MIN   68 <--->                      MIN  895        CONN
  868       85.2                      MIN 1063 ---->     PR63:  C9H4O3 + C20H17N3O     DISCONN
  869       85.2                      MIN   81 <--->                      MIN  638        CONN
  870       85.3                      MIN   90 <--->                      MIN  895        CONN
  872       85.4                      MIN  897 <--->                      MIN 1072        CONN
  873       85.5                      MIN  391 <--->                      MIN 1152        CONN
  875       85.7                      MIN 1068 <--->                      MIN 1153     DISCONN
  876       85.9                      MIN  471 <--->                      MIN 1207        CONN
  879       86.3                      MIN    7 <--->                      MIN  927        CONN
  880       86.3                      MIN  178 <--->                      MIN  715        CONN
  881       86.5                      MIN 1057 <--->                      MIN 1159        CONN
  882       86.6                      MIN  150 <--->                      MIN  772        CONN
  883       87.1                      MIN 1161 <--->                      MIN 1216     DISCONN
  884       87.1                      MIN  300 <--->                      MIN  830        CONN
  885       87.3                      MIN   70 <--->                      MIN  285        CONN
  886       87.4                      MIN  129 <--->                      MIN  981        CONN
  887       87.5                      MIN   26 <--->                      MIN 1182        CONN
  888       88.0                      MIN   40 <--->                      MIN  840        CONN
  889       88.1                      MIN  652 <--->                      MIN 1036        CONN
  890       88.3                      MIN    2 <--->                      MIN 1141        CONN
  891       88.4                      MIN  599 <--->                      MIN  916        CONN
  892       88.6                      MIN   40 <--->                      MIN 1169        CONN
  894       88.7                      MIN   31 <--->                      MIN  449        CONN
  895       88.7                      MIN  236 <--->                      MIN  849     DISCONN
  896       89.1                      MIN    1 <--->                      MIN 1100     DISCONN
  897       89.2                      MIN   40 <--->                      MIN  840        CONN
  898       89.2                      MIN   70 <--->                      MIN 1240        CONN
  899       89.8                      MIN   40 <--->                      MIN 1169        CONN
  900       89.8                      MIN  190 <--->                      MIN  856        CONN
  901       90.0                      MIN   46 <--->                      MIN  840        CONN
  902       90.1                      MIN  727 <--->                      MIN  695        CONN
  903       90.2                      MIN 1130 <--->                      MIN 1191        CONN
  904       90.2                      MIN  701 <--->                      MIN 1024     DISCONN
  906       90.6                      MIN   46 <--->                      MIN 1070        CONN
  907       90.8                      MIN  471 <--->                      MIN 1235        CONN
  908       91.0                      MIN  864 <--->                      MIN 1148     DISCONN
  909       91.1                      MIN   40 <--->                      MIN 1070        CONN
  911       91.1                      MIN   40 <--->                      MIN  840        CONN
  912       91.2                      MIN   40 <--->                      MIN  860        CONN
  913       91.2                      MIN  190 <--->                      MIN  856        CONN
  914       91.5                      MIN   46 <--->                      MIN  738        CONN
  915       91.6                      MIN   96 <--->                      MIN  999        CONN
  916       91.6                      MIN   46 <--->                      MIN  860        CONN
  918       91.7                      MIN   40 <--->                      MIN  860        CONN
  919       91.8                      MIN   40 <--->                      MIN  860        CONN
  920       91.8                      MIN   35 <--->                      MIN 1078     DISCONN
  921       92.1                      MIN  215 <--->                      MIN  832        CONN
  923       92.3                      MIN   20 <--->                      MIN  449        CONN
  924       92.3                      MIN  303 <--->                      MIN  991        CONN
  925       92.4                      MIN  183 <--->                      MIN  592        CONN
  927       92.6                      MIN  602 <--->                      MIN 1060        CONN
  928       92.7                      MIN  166 <--->                      MIN  828        CONN
  929       93.0                      MIN  727 <--->                      MIN  695        CONN
  930       93.0                      MIN   27 <--->                      MIN 1168        CONN
  931       93.0                      MIN  178 <--->                      MIN 1217        CONN
  932       93.3                      MIN   35 <--->                      MIN 1078     DISCONN
  933       93.4                      MIN    3 <--->                      MIN 1156        CONN
  934       93.6                      MIN  183 <--->                      MIN  592        CONN
  935       93.7                      MIN   46 <--->                      MIN  840        CONN
  936       93.7                      MIN   70 <--->                      MIN  285        CONN
  937       94.0                      MIN  842 <--->                      MIN 1226     DISCONN
  938       94.6                      MIN 1049 ---->       PR31:  H2O + C29H19N3O3     DISCONN
  940       95.0                      MIN   96 <--->                      MIN  545        CONN
  941       95.0                      MIN  215 <--->                      MIN 1203        CONN
  942       95.0                      MIN  580 <--->                      MIN 1082     DISCONN
  943       95.3                      MIN  215 <--->                      MIN  832        CONN
  944       95.4                      MIN  166 <--->                      MIN  828        CONN
  946       95.8                      MIN   96 <--->                      MIN  545        CONN
  948       96.1                      MIN  166 <--->                      MIN  902        CONN
  949       96.3                      MIN   96 <--->                      MIN  999        CONN
  950       96.6                      MIN   26 ---->    PR375:  C9H6O3 + C20H15N3O        CONN
  951       96.7                      MIN   40 <--->                      MIN  792        CONN
  952       96.8                      MIN  620 <--->                      MIN 1249     DISCONN
  953       97.3                      MIN  183 <--->                      MIN  592        CONN
  954       97.5                      MIN 1258 ---->      PR265:  H2O + C29H19N3O3     DISCONN
  955       97.6                      MIN 1195 ---->      PR112:  H2O + C29H19N3O3     DISCONN
  956       97.7                      MIN   40 <--->                      MIN  792        CONN
  957       97.7                      MIN   26 ---->    PR375:  C9H6O3 + C20H15N3O        CONN
  960       98.4                      MIN 1183 <--->                      MIN 1232     DISCONN
  961       99.0                      MIN 1194 <--->                      MIN 1229     DISCONN
  962       99.0                      MIN 1112 <--->                      MIN 1209        CONN
  963       99.0                      MIN 1186 ---->       PR288:  H2 + C29H19N3O4     DISCONN
  965       99.2                      MIN  197 <--->                      MIN  886     DISCONN
  966       99.2                      MIN  330 <--->                      MIN 1251        CONN
  969       99.9                      MIN  166 <--->                      MIN  828        CONN
  970       99.9                      MIN  853 <--->                      MIN 1133        CONN
  971      100.0                      MIN   27 <--->                      MIN 1091        CONN
  972      100.2                      MIN 1141 <--->                      MIN 1245        CONN
  973      100.2                      MIN  300 <--->                      MIN 1099        CONN
  975      100.9                      MIN  961 <--->                      MIN 1037     DISCONN
  976      101.2                      MIN 1200 ---->      PR237:  H2O + C29H19N3O3        CONN
  977      101.5                      MIN  602 <--->                      MIN 1060        CONN
  979      102.5                      MIN  130 <--->                      MIN  945        CONN
  981      102.7                      MIN  203 <--->                      MIN 1123        CONN
  982      103.1                      MIN   70 <--->                      MIN 1196        CONN
  983      103.1                      MIN  674 <--->                      MIN  889        CONN
  984      103.2                      MIN   27 <--->                      MIN  929        CONN
  985      103.4                      MIN  778 <--->                      MIN 1181     DISCONN
  986      103.5                      MIN  197 <--->                      MIN  996     DISCONN
  987      103.5                      MIN 1145 <--->                      MIN 1259     DISCONN
  988      103.7                      MIN 1205 <--->                      MIN 1231     DISCONN
  989      104.2                      MIN 1204 <--->                      MIN 1274     DISCONN
  990      104.3                      MIN  665 ---->    PR341:  C9H6O3 + C20H15N3O        CONN
  991      104.3                      MIN  369 <--->                      MIN 1140        CONN
  992      104.6                      MIN 1111 <--->                      MIN 1248     DISCONN
  993      104.8                      MIN   67 <--->                      MIN  462        CONN
  994      105.0                      MIN  427 <--->                      MIN 1114        CONN
  995      105.4                      MIN  300 <--->                      MIN  783        CONN
  996      105.5                      MIN 1132 <--->                      MIN 1190     DISCONN
  997      105.7                      MIN  995 ---->      PR169:  H2O + C29H19N3O3     DISCONN
  998      105.8                      MIN  665 ---->    PR289:  C9H6O3 + C20H15N3O        CONN
  999      105.9                      MIN  264 <--->                      MIN 1109        CONN
 1000      106.4                      MIN  890 <--->                      MIN  917        CONN
 1001      106.8                      MIN  330 <--->                      MIN 1115        CONN
 1002      107.1                      MIN  375 <--->                      MIN 1221        CONN
 1003      107.3                      MIN 1126 ---->       PR100:  CO + C28H21N3O3     DISCONN
 1004      107.3                      MIN  407 <--->                      MIN 1128        CONN
 1005      107.4                      MIN  965 ---->    PR267:  C9H6O3 + C20H15N3O        CONN
 1006      107.5                      MIN  386 <--->                      MIN 1269     DISCONN
 1007      107.6                      MIN  423 <--->                      MIN 1221        CONN
 1008      108.2                      MIN   20 <--->                      MIN 1118        CONN
 1009      108.4                      MIN   19 <--->                      MIN  116        CONN
 1011      108.8                      MIN 1228 <--->                      MIN 1275     DISCONN
 1013      109.4                      MIN   26 ---->    PR270:  C9H6O3 + C20H15N3O        CONN
 1014      110.6                      MIN   81 ---->      PR303:  CO2 + C28H21N3O2        CONN
 1015      110.7                      MIN   19 <--->                      MIN  116        CONN
 1017      110.9                      MIN  476 ---->    PR385:  C9H6O3 + C20H15N3O     DISCONN
 1018      111.0                      MIN  770 <--->                      MIN 1021        CONN
 1019      111.3                      MIN  359 ---->   PR336:  C8H4O2 + C21H17N3O2        CONN
 1020      111.9                      MIN  135 <--->                      MIN 1263        CONN
 1021      112.1                      MIN  244 ---->       PR328:  CO + C28H21N3O3        CONN
 1022      112.2                      MIN  400 <--->                      MIN 1167     DISCONN
 1023      112.5                      MIN  333 <--->                      MIN  512        CONN
 1024      112.5                      MIN   20 <--->                      MIN 1118        CONN
 1027      114.2                      MIN   31 <--->                      MIN  421        CONN
 1029      114.6                      MIN 1021 <--->                      MIN 1213        CONN
 1031      116.0                      MIN 1227 ---->      PR163:  H2O + C29H19N3O3     DISCONN
 1032      118.8                      MIN  300 ---->      PR21:  H2O2 + C29H19N3O2        CONN
 1033      118.8                      MIN  203 <--->                      MIN 1200        CONN
 1034      118.9                      MIN  427 <--->                      MIN 1292        CONN
 1035      119.0                      MIN  824 ---->    PR167:  C9H6O3 + C20H15N3O        CONN
 1036      119.4                      MIN   39 <--->                      MIN 1218        CONN
 1037      119.6                      MIN   67 <--->                      MIN 1291        CONN
 1038      120.0                      MIN  770 ---->    PR331:  C9H6O3 + C20H15N3O        CONN
 1040      120.5                      MIN  141 <--->                      MIN  372        CONN
 1041      120.6                      MIN 1201 ---->      PR125:  H2O + C29H19N3O3     DISCONN
 1042      120.9                      MIN  203 <--->                      MIN 1210        CONN
 1044      121.1                      MIN 1208 <--->                      MIN 1238     DISCONN
 1045      121.7                      MIN  770 ---->    PR325:  C9H6O3 + C20H15N3O        CONN
 1046      123.1                      MIN    2 ---->    PR116:  C9H6O3 + C20H15N3O        CONN
 1047      124.1                      MIN 1221 <--->                      MIN 1283        CONN
 1048      124.2                      MIN  141 ---->     PR14:  C9H6O3 + C20H15N3O        CONN
 1050      124.5                      MIN  671 ---->       PR170:  CO + C28H21N3O3     DISCONN
 1051      124.9                      MIN  380 <--->                      MIN 1192        CONN
 1053      126.7                      MIN  142 <--->                      MIN 1278        CONN
 1054      126.7                      MIN 1233 <--->                      MIN 1280     DISCONN
 1055      126.8                      MIN   39 <--->                      MIN 1284        CONN
 1056      127.4                      MIN 1233 <--->                      MIN 1272     DISCONN
 1057      128.7                      MIN 1215 ---->      PR316:  H2O + C29H19N3O3     DISCONN
 1058      129.5                      MIN  842 <--->                      MIN  921     DISCONN
 1059      131.0                      MIN 1242 <--->                      MIN 1282     DISCONN
 1060      131.5                      MIN  198 <--->                      MIN  504        CONN
 1061      132.2                      MIN 1244 ---->     PR74:  C9H6O3 + C20H15N3O     DISCONN
 1062      133.2                      MIN 1242 <--->                      MIN 1281     DISCONN
 1063      134.0                      MIN 1268 <--->                      MIN 1290     DISCONN
 1064      134.4                      MIN  179 <--->                      MIN 1262        CONN
 1066      135.3                      MIN 1119 ---->    PR135:  C9H6O3 + C20H15N3O     DISCONN
 1067      135.8                      MIN  811 <--->                      MIN 1253     DISCONN
 1068      136.6                      MIN 1250 <--->                      MIN 1288     DISCONN
 1069      137.1                      MIN 1250 <--->                      MIN 1288     DISCONN
 1070      137.6                      MIN  166 <--->                      MIN 1243        CONN
 1072      138.0                      MIN 1255 <--->                      MIN 1293     DISCONN
 1074      138.5                      MIN 1255 <--->                      MIN 1293     DISCONN
 1075      139.5                      MIN 1250 <--->                      MIN 1288     DISCONN
 1076      139.5                      MIN   27 ---->       PR20:  H2O + C29H19N3O3        CONN
 1077      139.7                      MIN 1198 <--->                      MIN 1279     DISCONN
 1078      141.7                      MIN  117 ---->     PR16:  C9H6O3 + C20H15N3O        CONN
 1079      144.1                      MIN 1266 <--->                      MIN 1297     DISCONN
 1080      144.5                      MIN  353 <--->                      MIN 1200        CONN
 1081      145.1                      MIN  728 ---->    PR224:  C9H6O3 + C20H15N3O        CONN
 1082      145.8                      MIN 1262 <--->                      MIN 1296        CONN
 1084      146.4                      MIN  673 <--->                      MIN 1273        CONN
 1085      146.9                      MIN 1262 <--->                      MIN 1298        CONN
 1086      150.6                      MIN 1287 ---->    PR190:  C9H6O3 + C20H15N3O     DISCONN
 1087      151.4                      MIN  203 <--->                      MIN 1301     DISCONN
 1088      152.2                      MIN 1179 <--->                      MIN 1301     DISCONN
 1089      153.1                      MIN  736 <--->                      MIN 1295     DISCONN
 1090      156.4                      MIN 1225 <--->                      MIN 1299     DISCONN
 1091      163.6                      MIN  745 <--->                      MIN 1303     DISCONN
 1092      174.3                      MIN 1138 <--->                      MIN 1300     DISCONN
